### ISSUE TITLE
Latest ISO causes UEFI to skip Boot Partition

### ISSUE THREAD

**Issue by Gitomu** [endeavouros-team/ISO-hotfixes#4]
I recently decided to go back to EndeavourOS and give it another chance as I used to build my Arch system from scratch.
Last time I used EndeavourOS was around February 2024 and the installation went smoothly. However, I decided to update to the latest ISO, so I downloaded it from the official website. I even checked and confirmed the hash was fine and there was nothing wrong with the ISO.
After installing it on my daily driver Gaming PC, the Calamares installer went great and I rebooted. To my surprise, I did not get any splash screen nor any services being loaded as every Arch system should start with. I found out you have to manually go into the Boot menu to select the partition where EndeavourOS was installed so I could finally boot from it. 
I made sure my UEFI settings were fine so that the boot partition could be recognized the next time, no luck; same issue happened.
This behavior has never happened before with Vanilla Arch or any other Arch based Distro like Manjaro, Arco Linux, Archcraft, CachyOS, etc. 

Not sure if this is only happening to me but it's certainly annoying and frustrating. I'd appreciate anyone checking on this issue and let me know once it gets fixed. 

Thanks a lot for your time and efforts to develop this Distro.

**Comment by dalto8** [comment]
This is not a common issue or indicative of something wrong with the ISO.  It is typically caused by the BIOS/firmware not updating the default.

Either way it is easily fixed by either changing the defaults in the BIOS or with `efibootmgr`

**Comment by killajoe** [comment]
could be the nvram to safe the entries is full.
So installer is not able to set a new default.. and also your try to set fails as it can not store it. 
In this case removing old unused entries manually from the firmware itself or using efibootmgr will resolve the issue. 
Needs indeed to rewrite the entry after the removal. Command will differ from bootloader used. Best in case you still have question or stuck in the process is to ask at the forum or on the telegram-chat

**Comment by Gitomu** [comment]
> This is not a common issue or indicative of something wrong with the ISO. It is typically caused by the BIOS/firmware not updating the default.
> 
> Either way it is easily fixed by either changing the defaults in the BIOS or with `efibootmgr`

What seems to be odd though is that no other Linux distro installation gives me this behavior, not even non Arch based distros. I've installed nearly every distro I can think of and I never had to change anything in the BIOS/firmware settings at all. They all boot just fine as they're able to find the EFI partition where the OS is installed. 
Anyways, not a big deal, I simply wanted to try Endeavour OS one more time to see what changed in all these months. I guess my hardware doesn't like this particular installation at all. 

I'll stick with vanilla Arch for now as I prefer to tweak the system on my own.

**Comment by killajoe** [comment]
you have not seen my comment? 
Okay.. 
Try again:
It could be that it was never happen **before**  as of the nvram was simply not full of old entries.. but over time it has filled up and now is not able to save entries anymore.. 
A lot of efi firmware implementations are terribly designed. They simply do not have in mind that people like us Distrohopping and go installing 10001 Os over a short time period..
